project_name: trailer
builds:
  - env:
      - CGO_ENABLED=0
    ldflags: 
    - -s -w -X main.build={{.Version}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    main: .

release:
  name_template: "v{{.Version}}"

archive:
  name_template: "{{.ProjectName}}-{{.Version}}-{{.Os}}-{{.Arch}}"
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip