dist: xenial 

language: go

go:
- 1.13.x

git:
  depth: 1

script:
  - go get -v -t -d ./... 

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux

notifications:
  email: false